# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Stephen Hockey
tagline:             'Data Science Portfolio'
description:         "A personal website containing the projects I've worked on since starting out as a data scientist."
url:                 http://stephenhockey.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Stephen Hockey
  url:               https://stephenhockey.github.io
  email:             stephen.hockey1@hotmail.com

# Custom vars
version:             1.0.0

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

paginate_path: "page:num" 
